import type { PlayDescriptor } from "../types";

export const defaultPlays: PlayDescriptor[] = [
  {
    playType: "personality_read",
    category: "text",
    title: "性格解读",
    description: "从头像的第一感觉出发，给你一段轻量性格侧写。",
    reason: "适合先用一句解读进入状态。",
    promptKey: "play.personality_read",
    tags: ["温和", "亲近", "明亮", "安静"],
  },
  {
    playType: "daily_fortune",
    category: "text",
    title: "今日运势",
    description: "给这张头像一张当天稳定的小运势卡。",
    reason: "适合快速看今天的氛围。",
    promptKey: "play.daily_fortune",
    tags: ["轻快", "明亮", "好运", "灵感"],
  },
  {
    playType: "social_aura",
    category: "text",
    title: "社交气场",
    description: "看看这张头像在别人眼里更像什么气场。",
    reason: "适合在意第一印象的人。",
    promptKey: "play.social_aura",
    tags: ["亲近", "自信", "神秘", "温暖"],
  },
  {
    playType: "style_swap",
    category: "image",
    title: "换风格头像",
    description: "保留你的辨识度，只切换整体风格。",
    reason: "适合想换新鲜感，但不想离原头像太远。",
    promptKey: "play.style_swap",
    tags: ["明亮", "时髦", "梦幻", "利落"],
  },
  {
    playType: "new_avatar",
    category: "image",
    title: "新头像生成",
    description: "以原头像为灵感，生成一张新的头像版本。",
    reason: "适合想看更明显变化的人。",
    promptKey: "play.new_avatar",
    tags: ["大胆", "主角感", "新鲜", "自信"],
  },
  {
    playType: "poster",
    category: "image",
    title: "海报生成",
    description: "把头像做成更有展示感的一张海报图。",
    reason: "适合想要更强视觉张力的人。",
    promptKey: "play.poster",
    tags: ["戏剧感", "大胆", "主角感", "时髦"],
  },
  {
    playType: "mood_mode",
    category: "image",
    title: "心情模式",
    description: "把情绪和氛围放大，生成一张单图。",
    reason: "适合想让画面更有情绪的人。",
    promptKey: "play.mood_mode",
    tags: ["轻快", "温柔", "氛围", "梦感"],
  },
  {
    playType: "story_mode",
    category: "image",
    title: "剧情模式",
    description: "把这张头像放进一个像故事截图的场景里。",
    reason: "适合想要一点画面叙事感的人。",
    promptKey: "play.story_mode",
    tags: ["戏剧感", "神秘", "主角感", "俏皮"],
  },
];
