import type { PlayDescriptor } from "../types";

export const defaultPlays: PlayDescriptor[] = [
  {
    playType: "personality_read",
    category: "text",
    title: "Personality Read",
    description: "A light personality snapshot drawn from your avatar's first impression.",
    reason: "Good for users who want to feel understood before they start playing.",
    promptKey: "play.personality_read",
    tags: ["friendly", "calm", "bright", "gentle"],
  },
  {
    playType: "daily_fortune",
    category: "text",
    title: "Daily Fortune",
    description: "A same-day-stable fortune card with a playful positive nudge.",
    reason: "Works well for repeat visits and quick entertainment.",
    promptKey: "play.daily_fortune",
    tags: ["upbeat", "bright", "lucky", "playful"],
  },
  {
    playType: "social_aura",
    category: "text",
    title: "Social Aura",
    description: "A light read on the vibe your avatar gives off in social spaces.",
    reason: "Fits users curious about first impressions and atmosphere.",
    promptKey: "play.social_aura",
    tags: ["friendly", "bold", "mysterious", "warm"],
  },
  {
    playType: "style_swap",
    category: "image",
    title: "Style Swap",
    description: "Keep the identity, switch the visual flavor into a fresh avatar style.",
    reason: "Best for users who want variety without losing familiarity.",
    promptKey: "play.style_swap",
    tags: ["bright", "stylish", "dreamy", "cool"],
  },
  {
    playType: "new_avatar",
    category: "image",
    title: "New Avatar",
    description: "Generate a newly interpreted avatar inspired by the uploaded portrait.",
    reason: "Great when the user wants a more transformed result.",
    promptKey: "play.new_avatar",
    tags: ["bold", "heroic", "fresh", "confident"],
  },
  {
    playType: "poster",
    category: "image",
    title: "Poster",
    description: "Turn the avatar into a stronger display-first poster composition.",
    reason: "Works for users who want a more dramatic showcase image.",
    promptKey: "play.poster",
    tags: ["dramatic", "bold", "heroic", "stylish"],
  },
  {
    playType: "mood_mode",
    category: "image",
    title: "Mood Mode",
    description: "Generate a single image focused on emotion and atmosphere.",
    reason: "Best for users who want the picture to lean into a clear feeling.",
    promptKey: "play.mood_mode",
    tags: ["upbeat", "gentle", "moody", "dreamy"],
  },
  {
    playType: "story_mode",
    category: "image",
    title: "Story Mode",
    description: "Generate a single image that feels like a snapshot from a scene.",
    reason: "Ideal for users who want a tiny narrative spark from one portrait.",
    promptKey: "play.story_mode",
    tags: ["dramatic", "mysterious", "heroic", "playful"],
  },
];
